name: decision-transformer-gym
channels:
- pytorch
dependencies:
- python=3.8.5
- anaconda
- cudatoolkit=11.8
- numpy
- pip
- pip:
  - gym==0.18.3
  - mujoco-py<2.2,>=2.1
  - numpy==1.20.3
  - torch==1.8.1
  - pytorch-cuda==11.8
  - transformers==4.5.1
  - wandb==0.9.1
  # - "--editable=git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl"
