name: decision-transformer-gym
channels:
- pytorch
- conda-forge
- powerai
- nvidia
dependencies:
- python=3.8.5
- anaconda
- cudatoolkit=12.1
- pytorch-cuda=11.8
- pytorch
- numpy
- pip
- pip:
  - gym==0.18.3
  - mujoco-py<2.2
  - numpy==1.20.3
  - transformers==4.5.1
  - wandb==0.9.1
  # - "--editable=git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl"
